move contrib

diff --git a/initcpio/install/zfsbootmenu b/initcpio/install/zfsbootmenu
--- a/initcpio/install/zfsbootmenu
+++ b/initcpio/install/zfsbootmenu
@@ -100,6 +100,16 @@ add_zbm_binaries() {
     map add_optional_binary "${maycopy[@]}"
 }
 
+add_optional_binary() {
+    # This has to be inverted to avoid a RETURN trap that triggers failure
+    if ! command -v "${1}" >/dev/null 2>&1; then
+        warning "optional component '${1}' not found, will omit"
+        return 0
+    fi
+
+    add_binary "${1}"
+}
+
 create_zbm_entrypoint() {
     # Create an entrypoint to initialize the ZBM environment
 
