Work in progress - ignore me

diff --git a/initcpio/install/zfsbootmenu b/initcpio/install/zfsbootmenu
--- a/initcpio/install/zfsbootmenu
+++ b/initcpio/install/zfsbootmenu
@@ -23,7 +23,7 @@ add_terminfo() {
     done
 }
 
-add_optional_binary() {
+add_optional_binaries() {
     # This has to be inverted to avoid a RETURN trap that triggers failure
     if ! command -v "${1}" >/dev/null 2>&1; then
         warning "optional component '${1}' not found, will omit"
@@ -31,6 +31,16 @@ add_optional_binary() {
     fi
 
     add_binary "${1}"
+}
+
+add_optional_file() {
+    # This has to be inverted to avoid a RETURN trap that triggers failure
+    if ! [ -f "${1}" ]; then
+        warning "optional file '${1}' not found, will omit"
+        return 0
+    fi
+
+    map add_file "${mustcopy[@]}"
 }
 
 add_optional_module() {
@@ -138,6 +148,12 @@ build() {
     # Binaries required for ZBM operation
     add_zbm_binaries
 
+    # shellcheck disable=SC2154
+    map add_file "${zfsbootmenu_essential_files[@]}"
+
+    # shellcheck disable=SC2154
+    add_optional_binaries "${zfsbootmenu_optional_files[@]}"
+
     # Add libgcc_s as appropriate
     local _libgcc_s
     if ! _libgcc_s="$( find_libgcc_s )"; then
@@ -183,21 +199,27 @@ build() {
     echo 'zfs' >>"${BUILDROOT}/etc/filesystems"
 
     # shellcheck disable=SC2154
-    for _file in "${zfsbootmenu_early_setup[@]}"; do
+    for _file in $zfsbootmenu_early_setup; do
         [ -x "${_file}" ] || continue
         add_file "${_file}" "/libexec/early-setup.d/${_file##*/}"
     done
 
     # shellcheck disable=SC2154
-    for _file in "${zfsbootmenu_setup[@]}"; do
+    for _file in $zfsbootmenu_setup; do
         [ -x "${_file}" ] || continue
         add_file "${_file}" "/libexec/setup.d/${_file##*/}"
     done
 
     # shellcheck disable=SC2154
-    for _file in "${zfsbootmenu_teardown[@]}"; do
+    for _file in $zfsbootmenu_teardown; do
         [ -x "${_file}" ] || continue
         add_file "${_file}" "/libexec/teardown.d/${_file##*/}"
+    done
+
+    # shellcheck disable=SC2154
+    for _file in $zfsbootmenu_before_kexec; do
+        [ -x "${_file}" ] || continue
+        add_file "${_file}" "/libexec/before_kexec.d/${_file##*/}"
     done
 
     compat_dirs=( "/etc/zfs/compatibility.d" "/usr/share/zfs/compatibility.d/" )
